platform :ios, '11.0'
swift_version = '5.0'

target 'MovesenseShowcase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Remote Movesense pod via git
  pod 'Movesense', :git => 'https://bitbucket.org/movesense/movesense-mobile-lib.git', :branch => 'master'

  # Local DFU pod via git
  pod 'MovesenseDfu', :git => '..', :branch => 'main'

  # Local DFU pod via path for development
  #pod 'MovesenseDfu', :path => '../MovesenseDfu.podspec'

end

target 'MovesenseShowcaseTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Remote Movesense pod via git
  pod 'Movesense', :git => 'https://bitbucket.org/movesense/movesense-mobile-lib.git', :branch => 'master'

  # Local DFU pod via git
  pod 'MovesenseDfu', :git => '..', :branch => 'main'

  # Local DFU pod via path for development
  #pod 'MovesenseDfu', :path => '../MovesenseDfu.podspec'

end

# Update all targets to Swift version 5.0 to stop Xcode version upgrade nagging
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
    end
  end
end