platform :ios, '10.0'
swift_version = '5.0'

target 'MovesenseDfu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'iOSDFULibrary', :git => 'https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library.git', :tag => '4.4.2'

end

target 'MovesenseDfuTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MovesenseDfu', :path => '../../MovesenseDfu.podspec'
  
end

# Update all targets to Swift version 5.0 to stop Xcode version upgrade nagging
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
    end
  end
end